from services.llm_explainer import generate_loan_explanation

def generate_loan_report(loan):

    explanation = generate_loan_explanation(loan)

    report = f"""
HEX CREDIT SYSTEM
Loan Evaluation Report

Customer: {loan["customer_name"]}
Loan Amount: ₹{loan["loan_amount"]}
Credit Score: {loan["credit_score"]}
Risk Level: {loan["risk"]}

AI Credit Analysis:

{explanation}

Decision Recommendation:
{loan["status"]}

Generated by HEX-Credit AI
"""

    return report